import {rawDatum} from "./types.ts";

export const compressionDebug: {[index: string]: number}[] = [
    { "r": 0, "g": 0, "b": 1 }, { "r": 0, "g": 0, "b": -1 }, { "r": 0, "g": 1, "b": 0 },
    { "r": 0, "g": 1, "b": 1 }, { "r": 0, "g": 1, "b": -1 }, { "r": 0, "g": -1, "b": 0 },
    { "r": 0, "g": -1, "b": 1 }, { "r": 0, "g": -1, "b": -1 }, { "r": 1, "g": 0, "b": 0 },
    { "r": 1, "g": 0, "b": 1 }, { "r": 1, "g": 0, "b": -1 }, { "r": 1, "g": 1, "b": 0 },
    { "r": 1, "g": 1, "b": 1 }, { "r": 1, "g": 1, "b": -1 }, { "r": 1, "g": -1, "b": 0 },
    { "r": 1, "g": -1, "b": 1 }, { "r": 1, "g": -1, "b": -1 }, { "r": -1, "g": 0, "b": 0 },
    { "r": -1, "g": 0, "b": 1 }, { "r": -1, "g": 0, "b": -1 }, { "r": -1, "g": 1, "b": 0 },
    { "r": -1, "g": 1, "b": 1 }, { "r": -1, "g": 1, "b": -1 }, { "r": -1, "g": -1, "b": 0 },
    { "r": -1, "g": -1, "b": 1 }, { "r": -1, "g": -1, "b": -1 }
];
export const openBorders: {[index: string]: string[]} = {
    "AL": ["GR", "MK", "ME", "XK"],
    "AT": ["DE", "CZ", "SK", "HU", "SI", "IT", "CH", "LI"],
    "AD": ["FR", "ES"],
    "AX": ["FI"],
    "BA": ["HR", "ME", "RS"],
    "BE": ["FR", "NL", "DE", "LU"],
    "BG": ["RO", "RS", "MK", "GR"],
    "BY": ["LT", "LV", "PL"],
    "CH": ["FR", "DE", "AT", "IT", "LI"],
    "CZ": ["DE", "PL", "SK", "AT"],
    "DE": ["DK", "NL", "BE", "LU", "FR", "CH", "AT", "CZ", "PL"],
    "DK": ["DE"],
    "EE": ["LV"],
    "ES": ["PT", "FR", "GI", "AD"],
    "FI": ["NO", "SE", "AX"],
    "FR": ["BE", "LU", "DE", "CH", "IT", "MC", "ES", "AD"],
    "GB": ["IE"],
    "GI": ["ES"],
    "GR": ["AL", "MK", "BG"],
    "HR": ["SI", "HU", "RS", "BA", "ME", "IT"],
    "HU": ["AT", "SK", "RO", "RS", "HR", "SI"],
    "IE": ["GB"],
    "IT": ["FR", "CH", "AT", "SI", "SM", "VA", "HR"],
    "LI": ["CH", "AT"],
    "LT": ["LV", "BY", "PL"],
    "LU": ["BE", "FR", "DE"],
    "LV": ["EE", "LT", "BY"],
    "MC": ["FR"],
    "ME": ["HR", "BA", "RS", "XK", "AL"],
    "MK": ["AL", "GR", "BG", "RS", "XK"],
    "NL": ["BE", "DE"],
    "NO": ["FI", "SE"],
    "PL": ["DE", "CZ", "SK", "LT", "BY"],
    "PT": ["ES"],
    "RO": ["BG", "RS", "HU"],
    "RS": ["HR", "BA", "HU", "RO", "BG", "MK", "XK", "ME"],
    "SE": ["NO", "FI"],
    "SI": ["IT", "AT", "HU", "HR"],
    "SK": ["CZ", "PL", "HU", "AT"],
    "SM": ["IT"],
    "VA": ["IT"],
    "XK": ["RS", "ME", "AL", "MK"],
    "IN": ["NP"],
    "NP": ["IN"],
    "BR": ["AR"],
    "AR": ["BR"],
    "MF": ["SX"],
    "SX": ["MF"]
};
export const testData: rawDatum[] = [
    {"id":  1, "lat":   37.945522, "lon":   23.668790, "cc": "GR"},
    {"id":  2, "lat":   59.506506, "lon":   17.921503, "cc": "SE"},
    {"id":  3, "lat":   39.186710, "lon":  -77.252235, "cc": "US"},
    {"id":  4, "lat":   41.687879, "lon":  -91.611682, "cc": "US"},
    {"id":  5, "lat":   54.935841, "lon":   -1.369136, "cc": "GB"},
    {"id":  6, "lat":   13.870685, "lon":  100.558653, "cc": "TH"},
    {"id":  7, "lat":   28.995286, "lon":  -13.491310, "cc": "ES"},
    {"id":  8, "lat":  -33.910880, "lon":  151.207500, "cc": "AU"},
    {"id":  9, "lat":  -33.788149, "lon":  151.285844, "cc": "AU"},
    {"id": 10, "lat":   24.481564, "lon":  118.125030, "cc": "CN"},
	{"id": 11, "lat":   42.350116, "lon":  -77.669345, "cc": "US"},
	{"id": 12, "lat":    9.537782, "lon":  100.069772, "cc": "TH"},
	{"id": 13, "lat":   36.639637, "lon":  -93.269216, "cc": "US"},
	{"id": 14, "lat":   38.485672, "lon": -107.868173, "cc": "US"},
    {"id": 15, "lat":   22.391,    "lon":  114.137,    "cc": "HK"}, // Should return HK happily
    {"id": 16, "lat":    1.472,    "lon":  103.887,    "cc": "SG"}, // Lat lon in Johor Bahru, MY
    {"id": 17, "lat":   32.602,    "lon": -115.214,    "cc": "US"}, // Lat lon in MX
    {"id": 18, "lat":   48.473,    "lon":    8.130,    "cc": "DE"}, // Strasbourg, FR, but CC is DE
];